name: Price Observer CI
run-name: ${{ github.actor }} is runnning tests for Price Observer application
on:
  push:
    branches:
      - main
    paths:
      - "priceObserver/**"
      - ".github/workflows/price-observer-ci.yml"
  pull_request:
    branches:
      - main
    paths:
      - "priceObserver/**"
      - ".github/workflows/price-observer-ci.yml"
jobs:
  CI-for-Price-Observer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: priceObserver
    env:
      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      ADMIN_TEST_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      ADMIN_PASSWORD_HASH: ${{ secrets.ADMIN_PASSWORD_HASH }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: price_observer
      LOG_LEVEL: DEBUG
      APP_PORT: 8000
    steps:
      - name: Download repository code
        uses: actions/checkout@v6
      - name: Build Docker Image
        run: docker compose build
      - name: Run migrations
        run: docker compose run --rm migrate
      - name: Run tests
        run: docker compose run --rm test
